CREATE TABLE IF NOT EXISTS products(
  id INT PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC(10,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS users(
  id INT PRIMARY KEY,
  email TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS orders(
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id),
  total_cents INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
