name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install pipx for tooling
        run: python -m pip install --upgrade pip
      - name: Wait for Postgres and create DBs
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432; do sleep 1; done
          PGPASSWORD=postgres psql -h localhost -U postgres -c 'CREATE DATABASE node_ecom;'
          PGPASSWORD=postgres psql -h localhost -U postgres -c 'CREATE DATABASE logistics_db;'
          PGPASSWORD=postgres psql -h localhost -U postgres -c 'CREATE DATABASE fintech_db;'
      - name: Make scripts executable
        run: chmod +x scripts/*.sh projects/**/scripts/*.sh || true
      - name: Verify all
        env:
          DATABASE_URL_NODE: postgresql://postgres:postgres@localhost:5432/node_ecom
          DATABASE_URL_PY: postgresql://postgres:postgres@localhost:5432/logistics_db
          DATABASE_URL_JAVA: jdbc:postgresql://localhost:5432/fintech_db
          PGUSER: postgres
          PGPASSWORD: postgres
        run: ./scripts/verify_all.sh
