name: Scenario Matrix

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        shell: bash
        run: |
          set -euo pipefail
          files=$(ls -1 projects/**/scenario.yml 2>/dev/null | jq -R -s -c 'split("\n")[:-1] | map({file: .})')
          if [ -z "$files" ] || [ "$files" = "null" ]; then files='[]'; fi
          echo "matrix=$files" >> "$GITHUB_OUTPUT"

  validate-render:
    needs: discover
    if: ${{ fromJson(needs.discover.outputs.matrix) != null }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.discover.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run scenario:validate
      - run: npm run scenario:render
      - uses: actions/upload-artifact@v4
        with:
          name: playbooks
          path: docs/generated/
